---
apiVersion: v1
kind: Pod
metadata:
 name: memorydemo
 labels:
   name: mem-demo
spec:
 containers:
   - name: mem-demo-ctr
     image: nginx:1.25
     resources:
      requests:
       memory: "128Mi"
     ports:
       - containerPort: 80
         protocol: TCP
   
