---
apiVersion: v1
kind: Service
metadata: 
  name: jenkins-svc
  labels:
    app: jenkins
spec:
  type: Nodeport
  ports:
    - name: jenkinsport
      nodePort: 30001
      port: 8080
      targetPort: 8080
      protocol: TCP


