---
apiVersion: v1
kind: Pod
metadata:
  name: mypod
# here labels are given to identify pod with labels.(bcos there might be many pods with same names in diff envments.we can easily identify pods with labels)
  labels:
    name: pod1
    env: dev
spec:
 containers:
   - name: jenkinscontainer
     image: jenkins/jenkins
     ports: 
       - containerPort: 8080
         hostPort: 8080
         protocol: TCP 