apiVersion: v1
kind: Service
metadata:
  name: spc-svc
  labels:
    app: spcapp
spec:
  type: NodePort
  selector:
    app: spc1
  ports:
    - targetPort: 8080
      port: 8080
      nodePort: 32024
