apiVersion: apps/v1
kind: Deployment
metadata:
  name: spc-deploy
  labels:
    app: spc
spec:
  minReadySeconds: 2
  replicas: 3
  selector:
    matchLabels:
      app: spc1
  template:
    metadata:
      name: spcpod
      labels:
        app: spc1
    spec:
      containers:
      - name: spccon
        image: divyak123/spring:latest
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "1000m"
        ports:
          - containerPort: 8080
            protocol: TCP
