apiVersion: v1
kind: Pod
metadata:
  name: mysqlpod
  labels:
    app: mysql
spec:
  containers:
    - name: mysqlcon
      image: 301675576809.dkr.ecr.ap-south-1.amazonaws.com/mysql:8
      env:
        - name: MYSQL_DATABASE
          value: 'nop'
        - name: MYSQL_USER
          value: 'nop'
        - name: MYSQL_PASSWORD
          value: 'nop123'
        - name: MYSQL_ROOT_PASSWORD
          value: 'nop123'
      ports:
         - name: dbport
           containerPort: 3306
           protocol: TCP
     